### ISSUE TITLE
Handling of face quadrature rule within scratch_data

### ISSUE THREAD

**Issue by mschreter** [MeltPoolDG/MeltPoolDG#185]
... this is related to #184 to get rid of the additional `dim_q` template argument.

https://github.com/MeltPoolDG/MeltPoolDG/blob/de32c620c55d64168c0b0abf6d38cf1dd4fe0df0/include/meltpooldg/interface/scratch_data.hpp#L76-L84

**Comment by peterrum** [comment]
I think we should be able to query this info from `MatrixFree` now.
