### ISSUE TITLE
DataComponentInterpretation

### ISSUE THREAD

**Issue by mschreter** [MeltPoolDG/MeltPoolDG#25]
The aim is to export vector_valued data as vectors to paraview and replace e.g. the following lines.
```cc
data_out.add_data_vector(dof_handler,
                            advection_velocity.block(d),
                            "advection_velocity_" + std::to_string(d));
```

To this end, a mini example will be setup where the utility will be tested.

**Comment by peterrum** [comment]
This will - officially - not come. Closing.
