### ISSUE TITLE
Separate multi-phase-flow framework

### ISSUE THREAD

**Issue by mschreter** [MeltPoolDG/MeltPoolDG#47]
- [x] **own operator for e.g. level set should support both matrix-free and matrix-based (?)**
- [x] step-by-step move of code (tests should still run)
- [ ] support of both BDF2<>generalized alpha (and make sure that the results stay the same!)
- [x] find out why does MeltPoolDG level set solution fed into adaflo not converge
- [ ] how to structure adaflo? we would like to have access to the different solvers (operation and operator, similar to MeltPoolDG)
- [x] **MeltPoolDG should have access to individual components (level set, phase field)**
- [ ] **Aim: generic interface for (multi-phase)-flow problems which can be combined**
- [ ] **Should adaflo grow? e.g. DG for level set/phase-field (+fluid) framework?** 
- [x] AMR
- [x] Simplex??

1. create classes with constructors taking indices
2. we start with the simplest operator and use this as template for the other problems
3. code should not be slower than before
4. tests should still run
5. AMR, umziehen, Simplex behalten und (Temperatur)
6. link adaflo dynamically to meltpool

**Comment by peterrum** [comment]
One additional point. I would suggest to pass our own `MatrixFree` instance to adaflo's `NavierStokes` solver (this is possible via `initialize_matrix_free`). This would let us reduce memory consumption and keep `MatrixFree` objects consistent throughout the application.

PR https://github.com/kronbichler/adaflo/pull/24 will allow to pass our own dof/quad indices of the velocity and pressure field.

**Comment by mschreter** [comment]
Todo for tomorrow:

- [ ] ARM of advection-diffusion
- [ ] couple normal vector module of adaflo to MeltPoolDG
- [ ] couple curvature module of adaflo to MeltPoolDG
- [ ] couple reinitialization module of adaflo to MeltPoolDG
- [ ] setup level set operation depending on adaflo modules
- [ ] How should we proceed with matrix-based adaflo algorithms?

**Comment by peterrum** [comment]
- Finalizing the advection (diffusion) operator should not take too much time. Later today, I'll check out the current version of the wrapper.
- Hopefully, once we agreed on design of the advection operator, the levels-set operator should be easy (or easier).
- Navier-Stokes: see also my comment from above.
- Matrix-based: I guess the best solution would be to extract the relevant code snippets into own modules (like we did last week) and select the matrix-free or matrix-based version here: https://github.com/MeltPoolDG/MeltPoolDG/blob/0deb40d6e064923303013a424679a32590af00f8/include/meltpooldg/advection_diffusion/advection_diffusion_problem.hpp#L239-L267
(but my suggestion would be to get all the other points running first)

**Comment by mschreter** [comment]
Fix bugs:

- [ ] reinit amr matrix-based
- [ ] advection-diffusion amr matrix-based
