### ISSUE TITLE
Thermo-Fluid Coupling 

### ISSUE THREAD

**Issue by mschreter** [MeltPoolDG/MeltPoolDG#99]
Implementation:
- [x] PR heat + velocity 
- [x] `heat_transfer_operator.hpp`: if `level_set_as_heaviside` density = ... capacity =...
- [x] `parameters.hpp`: two substructs `liquid` and `gas` with properties; they can be filled from `MeltPoolData` if available (define in `process_parameters_file`).
- [x] `heat_operation.hpp`: add configuration with level_set -- separate constructor?
- [x] `heat_operation.hpp`: add function `set_heat_source` to take heat sources, e.g. from laser impact
- [x] `melt_pool_operation.hpp`: integrate `heat_transfer_operation.hpp` for computing the resulting temperature field
- [x] `evaporation_operation.hpp`: `compute_evaporative_mass_flux_from_temperature_gradient` using Stefan-Neumann condition and latent heat of melting
- [x] `heat_operator.hpp`: add potential divergence of velocity field
- [x] `two_phase_flow_with_heat_transfer_operation.hpp`

Benchmark problems:
- [x] Thermo-Fluid: Marangoni convection heated droplet (Na, Tryggvason 2003)
- [x] MeltPool: Melting of a metal plate

Later:
- [x] Thermo-Fluid with phase change: Stefan's problem (Gibou 2007); Evaporating Droplet (Gibou 2007); Film boiling (Gibou 2007)

**Comment by nmuch** [comment]
- [ ] Add solidification to heat operator #141 
- [ ] Add linearizations for temperature dependent material properties (stationary) #141 
- [ ] Add apparent capacity method for latent heat
- [ ] Create free function that contains the body of the cell loop
- [ ] Add linearizations for temperature dependent material properties (with velocity)
- [ ] Enable two-phase flow and solidification in heat operation
